import { Injectable } from '@angular/core';

@Injectable()

export class EquiposService {

    constructor() {
        console.log('Servicio listo para usar!');
    }

    private equipos: Equipo[] = [
        {	nombre: 'Boca Juniors',
      fundacion: '3 de abril de 1905',
      barrio: 'La Boca', // tslint:disable-next-line:indent
	imgescudo: 'assets/img/boca.png',
      bio: 'Lo que hicieron Esteban Baglietto, Alfredo Scarpatti, Santiago Sana y los hermanos Teodoro y Juan Antonio Farenga aquel  3 de abril de 1905 no fue muy distinto a lo que por entonces hacían otros grupos de amigos por el resto de la Argentina para canalizar un incontenible fervor popular por el fútbol.Fundaban un club de fútbol. La particularidad del caso fue que, sin saberlo, estaban creando el más grande de la Argentina. Uno que se volvería pasión de multitudes y también un gigante mundial. Como la reunión en la casa de Baglietto fue interrumpida por inoportunas visitas, la ceremonia de fundación siguió al aire libre, en un banco de la Plaza Solís, y allí se fijó el nombre, tomado prestado del barrio, más ese Juniors que le daba un toque de prestigio inglés tan acorde con la época. Baglietto fue designado presidente. Y el 21 de abril de 1905, en el campo de juego de Independencia Sud, goleó 4-0 a Mariano Moreno en el primer partido de la historia. Un presagio de los tiempos por venir. ',
      camiseta: 'assets/img/camisetaboca.png',
      historiacamiseta: 'Juan Rafael Brichetto, presidente del club xeneize en 1907, luego de varios intentos por la elección de la camiseta, propuso dejar tal decisión al azar. Brichetto era operador de uno de los puentes del puerto lo que le dió la idea definitiva. Propuso adoptar los colores de la bandera del primer buque al que él le diera paso al día siguiente. Como vemos, el barco resultó ser sueco, por lo que Boca terminó llevando los colores azul y oro en franja. Sin embargo, el diseño original fue de una camiseta con franja cruzada, similar a la de River, que luego fue alterada hasta lograr el actual diseño del club de la Boca.',
      imgestadio: 'assets/img/bombonera.png',
      nomestadio: 'Estadio Alberto J. Armando',
      ubicacion: 'Brandsen 805, Capital Federal',
      fechaestadio: '25 de mayo 1940',
      apodo: 'Xeneizes o Bosteros',
      imghinchada: 'assets/img/bosteros.png',
      explicacion: 'Lo de xeneizes tiene que ver con el origén genovés de sus fundadores. A los inmigrantes de la región de Génova se les dice "xeneizes" y desde allí vinieron muchos de los que pusieron en marcha al club en 1905.Lo de "bosteros" nació como un canto hiriente de la hinchada de River hacia la de Boca por las inundaciones productos de las sudestadas. Con el tiempo, la gente de Boca lo tomó con orgullo. ',
      idolo: 'Juan Roman Riquelme',
      imgidolo: 'assets/img/roman.png',
      descripidolo: 'Riquelme se formó en las divisiones inferiores de Argentinos Juniors, para más tarde debutar en el Club Atlético Boca Juniors en 1996. En el club xeneize, Román pasó seis años donde ganó seis títulos, tres locales (Apertura 1998, Apertura 2000, Clausura 1999) y tres internacionales (Copas Libertadores 2000, 2001 y Copa Intercontinental 2000). Riquelme fue una figura importante entre todos esos campeonatos, potenciado principalmente por el entrenador Carlos Bianchi. En 2002, fue traspasado al Fútbol Club Barcelona, donde tan solo permaneció una temporada por sus problemas con el entrenador del equipo en esa época, Louis van Gaal. Se marchó cedido al Villareal, un club modesto de España donde consiguió sus mayores éxitos en Europa, ganando la Copa Intertoto y alcanzando las semifinales de la UEFA Champions League. En 2007, Román retornó a Boca y ganó su tercera Copa Libertadores de manera autoritaria, siendo el goleador del equipo y la pieza fundamental. En su tercer ciclo en el club, consiguió la Recopa Sudamericana 2008 y los torneos Apertura 2008 y Apertura 2011. Acabó yéndose en 2014, consagrándose como el máximo ídolo de la historia xeneize, siendo el 6º jugador con más presencias del club con 388, y el 7º con más títulos (con 11). Se retiró en Argentinos Juniors, el club de sus orígenes, donde consiguió el ascenso a la Primera División. '
},
{     nombre: 'River Plate',
      fundacion: '25 de mayo de 1901',
      barrio: 'Núñez',
      imgescudo: 'assets/img/river.png',
      bio: 'La Historia del Club Atlético River Plate comenzó el 25 de mayo de 1901, cuando de la unión de dos clubes amateurs (Santa Rosa y La Rosales) un grupo de 24 muchachos se reunió en Almirante Brown 927 -donde funcionaba la imprenta Francisco Gentile- con el objetivo de dar nacimiento a un nuevo club de fútbol. El nombre fue motivo de discusión para los fundadores: José Corpucci propuso River Plate; Carlos Antelo, La Rosales; Pedro Ratto, Forward y Bernardo Messina, Juventud Boquense. Se eligió el de River Plate y la institución se comenzó a llamar Club Atlético River Plate. Su primer presidente fue Leopoldo Bard.',
      camiseta: 'assets/img/camisetariver.png',
      historiacamiseta: 'Existen diversas teorías del nacimiento de la franja roja de la camiseta millonaria. Algunos expertos afirman que fue decisión de Enrique Salvarezza en 1905, otros creen que los colores fueron tomados del signo de San Jorge de Génova por los miembros originales del club de origen genovés. Sin embargo, existe una tercer historia, mucho más interesante, que habla de un viejo carnaval celebrado en una noche de 1908, donde una cinta roja de seda colgaba de la parte trasera de un auto. Cinco chicos que habían ido a disfrutar de la fiesta, vieron tal seda y la tomaron prestada en una travesura. Hasta entonces, la camiseta de River era completamente blanca, por lo que decidieron colocar la seda roja en forma diagonal con el objetivo de crear alguna característica diferencial en la casaca.',
      imgestadio: 'assets/img/monumental.png',
      nomestadio: 'Estadio Antonio Vespucio Liberti',
      ubicacion: 'Avda. Figueroa Alcorta 7597',
      fechaestadio: '26 de mayo de 1938',
      apodo: 'Millonario o Gallina',
      imghinchada: 'assets/img/gayinas.png',
      explicacion: 'River se ganó su apodo de "Millonario" en la década del 30, cuando pagó 35.000 por el pase de Bernabé Ferreyra, una verdadera fortuna para aquella época."Gallinas" se impuso en 1966, cuando les largaron una ponedora tras el arco de Gatti luego de perder con Peñarol 4-2 en la final de la Copa Libertadores. ',
      idolo: 'Norberto Alonso',
      imgidolo: 'assets/img/alonso.png',
      descripidolo: 'Entre sus logros personales se destacan haber sido Balón de Plata Sudamericano en 1975, campeón mundial con la selección argentina en 1978, campeón de América y campeón intercontinental con River Plate en 1986. Alonso es, junto a Ángel Labruna, Enzo Francescoli y Amadeo Carrizo uno de los ídolos generacionales más importantes de River Plate9​ y formó junto a Diego Maradona y Ricardo Bochini la trilogía de los más destacados "10" del fútbol argentino durante los años 70 y 80.Actualmente se desempeña como asesor presidencial y de imagen de River Plate en eventos y relaciones públicas a nivel internacional.',
      },
{     nombre: 'Independiente',
      fundacion: '4 de agosto de 1904',
      barrio: 'Avellaneda',
      imgescudo: 'assets/img/rojo.png',
      bio: 'Un 4 de agosto, pero de 1904,se inauguró un nuevo local de la tienda “A la Ciudad de Londres”, en la esquina sudeste de Avenida de Mayo y Perú, con entradas por Avenida de Mayo 570 y 600, Victoria 599 y Perú 92. Una gran tienda con estilo europeo donde se conseguían trajes, vestidos, zapatos, toda la moda masculina y femenina.Las grandes tiendas de la época nutrían con mano de obra nacional a nuevos equipos de fútbol que irían desplazando la preeminencia británica de las empresas y colegios extranjeros. Sus jugadores dejaban de entre apellidos ingleses para que sean castizos y latinos en general.',
      camiseta: 'assets/img/camisetarojo.png',
      historiacamiseta: 'Nottingham Forest, club inglés, vino de visita a la Argentina en 1908 para jugar un amistoso ante Alumni, en el cual lo derrotó con un contundente 6 a 0. Entre el público de ese partido se encontraba Arístides Langone, actual presidente de Independiente, quien quedó fascinado con la forma de jugar del equipo y de los uniformes rojos que utilizaban los jugadores. Fue esa admiración la que lo llevó a tomar la decisión de vestir a Independiente con sus mismos colores. El nacimiento de la camiseta del Rojo de Avellaneda fue en un partido que acabó 9 a 2 contra Banfield, fue el inicio de lo que sería una gran historia para la camiseta del Rojo de Avellaneda.',
      imgestadio: 'assets/img/libertadoresamerica.png',
      nomestadio: 'Estadio Libertadores de America',
      ubicacion: 'Bochini 751, Avellaneda',
      fechaestadio: '13 de abril de 1905',
      apodo: 'Diablos Rojos o Rey de Copas',
      imghinchada: 'assets/img/bojos.png',
      explicacion: 'El periodismo fue el responsable de que a Independiente se lo denominara el Diablo. En 1926, el equipo contaba con una delantera "endiablada" con Canaveri, Lalín, Ravaschino, Seoane y Orsi que hizo surgir el apodo."Rey de Copas" nace en la década del 70 por la gran cantidad de títulos internacionales logrados. ',
      idolo: 'Ricardo Bochini',
      imgidolo: 'assets/img/bochini.png',
      descripidolo: 'ampliamente considerado como el mejor jugador de toda la historia de Independiente, y como uno de los más grandes jugadores de todos los tiempos. Su puesto era de enganche, pasando a la historia como uno de los representantes más sobresalientes del puesto, y convirtiéndose en un arquetipo del jugador que lleva la camiseta N°10.Debutó en 1972 en Independiente, club donde jugó toda su carrera, uno de los pocos casos entre los jugadores de todo el mundo. En Independiente fue protagonista de la "era dorada" del club, y las competencias conquistadas por esa época lo tuvieron como protagonista. Bochini tuvo una carrera excepcional para un futbolista, ganando una enorme cantidad de títulos tanto nacionales como internacionales: con Independiente ganó 5 Copas Libertadores (1972, 1973, 1974, 1975 y 1984), 3 Copas Interamericanas (1974, 1975 y 1976), 2 Copas Intercontinentales (1973 y 1984), 2 campeonatos de Primera División Argentina (1983 y 1989) y 2 campeonatos Nacionales (1977 y 1978).Con la selección argentina de fútbol fue internacional desde 1973 hasta 1986, y ganó el Mundial de México 86.Se retiró en 1991, dejando atrás 19 años como uno de los más grandes símbolos del fútbol a nivel mundial, en una carrera donde jugó 714 partidos y metió 108 goles, más las innumerables asistencias que brindó a su equipo.',
      },
{     nombre: 'Racing Club',
      fundacion: ' 25 de marzo de 1903',
      barrio: 'Avellaneda',
      imgescudo: 'assets/img/racing.png',
      bio: 'La zona en la que se dieron los primeros pasos de la historia de Racing aún no era Avellaneda, sino que el territorio lindante con el Riachuelo se conocía como Barracas al Sur. Un grupo de empleados del Ferrocarril Sud les solicitó a las autoridades la cesión de unos terrenos para jugar allí al fútbol en los descansos. La respuesta afirmativa abrió el camino para demarcar la cancha y comenzar con los primeros desafíos, preferentemente ante equipos con mejores valores (generalmente ingleses), con el fin de enriquecerse a partir de estos enfrentamientos.',
      camiseta: 'assets/img/camisetaracing.png',
      historiacamiseta: 'En 1910, el club de Avellaneda decidió usar para su indumentaria los colores celeste y blanco de la Argentina, en honor al centenario de la Primera Junta. Lo curioso es que antes de llegar a esta camiseta, Racing había experimentado con cuatro camisetas distintas, una blanca, una rayada negra y amarilla como Peñarol de Uruguay, una celeste y salmón a cuadros grandes y una azul con franja blanca, igual a la camiseta suplente de Gimnasia de la Plata.',
      imgestadio: 'assets/img/cilindro.png',
      nomestadio: 'Estadio Presidente Perón',
      ubicacion: ' Pasaje Mozart y Corbatta,Avellaneda',
      fechaestadio: '13 de Septiembre de 1950',
      apodo: 'La Academia',
      imghinchada: 'assets/img/laacade.png',
      explicacion: 'El mote de "Academia" nace en 1913, cuando el equipo ganó siete títulos consecutivos. Ningún otro club en el mundo había alcanzado semejante logro. En los 60 fue el “equipo de José” por los logros de su mentor, Juan José Pizzutti. ',
      idolo: 'Diego Milito',
      imgidolo: 'assets/img/milito.png',
      descripidolo: 'Ya desde el inicio de su carrera se destacó por el freno y la cabeza levantada. Luego, le sumó el olfato goleador que fue mejorando con los años, sobre todo en Europa, donde se destaca. Nació el 12 de junio de 1979 en Bernal, Buenos Aires. En Racing jugó 148 partidos y anotó 37 goles. De ellos, ocho fueron en la Libertadores, con dos tantos, y tres en la Sudamericana, con una conquista.Debutó el 11 de diciembre de 1999, pasó los momentos de quiebra como un juvenil, fue parte activa del equipo que escapó a la promoción en la primera parte de 2001 y fundamental en el que fue campeón en la segunda parte de ese año. No solo jugó en Racing Club, club que lo vió nacer, sino que se desempeñó en Genoa, Real Zaragoza e Inter de Milán, siendo este ultimo club el que lo consagro en 2010 campeón de la Champions League..El 14 de diciembre de 2014 Racing enfrentó en el Cilindro a Godoy Cruz con la mente puesta en salir campeón. El estadio estaba lleno 2 horas y media antes del inicio del partido. Milito como máximo referente se puso el equipo al hombro en un estadio con más de 60.000 personas. La Academia ganó el partido ante el Tomba por 1-0 con gol de Ricardo Centurión y así volvió a ser campeón después de 13 años de la mano del Príncipe como máximo estandarte e ídolo del equipo, convirtiéndose en el último jugador de Racing en ser dos veces campeón con el club'
      },
{     nombre: 'San Lorenzo',
      fundacion: '1 de abril de 1908',
      barrio: 'Almagro - Boedo - Bajo Flores',
      imgescudo: 'assets/img/sanloro.png',
      bio: 'A principios de 1907, un grupo de jóvenes entusiastas liderados por Federico Monti y Antonio Scaramusso pasaba horas y más horas jugando al fútbol en la intersección de las calles México y Treinta y Tres Orientales. Ahí nacieron Los Forzosos de Almagro, como se autodenominaban, con un lema que decía: "Hay que romperse todo para vencernos". La historia de esta pandilla daría un giro divino gracias a la visión social de Lorenzo Bartolomé Martín Massa, el padre salesiano que buscaba sacar a los chicos de los peligros de la calle. ¿Cómo lo hizo? Abriendo las puertas del Oratorio San Antonio para que los pibes practicaran deportes a cambio de asegurar su presencia en la misa los domingos. Así, el 1° de abril de 1908, luego de una asamblea extraordinaria, el club pasó a llamarse San Lorenzo de Almagro.',
      camiseta: 'assets/img/camisetasanloro.png',
      historiacamiseta: 'La famosa camiseta azulgrana de San Lorenzo tiene una historia muy vinculada al origen mismo del nombre de San Lorenzo. El cura Lorenzo Bartolomé Martín Massa creía que el fútbol era una forma de llegar a los jovenes, por lo que decidió acompañar, apoyar y aconsejar el club originalmente de Almagro que se llamaba a si mismo "Los Forzosos de Almagro", nombre que no era del agrado de todos. El padre Massa fue el primero que donó un juego de camisetas al club, siendo estas del color azulgrana, color que el equipo decidió adoptar por el resto de su historia.',
      imgestadio: 'assets/img/gasometro.png',
      nomestadio: 'Estadio Pedro Bidegain',
      ubicacion: 'Av. Perito Moreno y Av. Varela',
      fechaestadio: '16 de diciembre de 1993',
      apodo: 'Azulgrana, Ciclón o Cuervos',
      imghinchada: 'assets/img/cuervos.png',
      explicacion: 'Azulgrana, obviamente por los colores de la camiseta.Lo de "Cuervos" se relaciona a la similitud en el color negro entre ese pájaro y las sotanas sacerdotales del padre Lorenzo Mazza, fundador del club. Y lo de "Ciclón" surgió para contrarrestar a su clásico rival: Huracán. Los hinchas del San Lorenzo se autobautizaron así porque según la ciencia, los Ciclones abarcan mayor área que los Huracanes.',
      idolo: 'Leandro Romagnoli',
      imgidolo: 'assets/img/pipiroma.png',
      descripidolo: 'La mayor parte de su carrera la desarrolló en el Club Atlético San Lorenzo de Almagro, siendo el jugador con más títulos obtenidos en la historia del club y considerado como el máximo ídolo de la institución.En su carrera, ha sido campeón de la Copa Libertadores, la Copa Mundial Sub-20, la Primera División, la Copa Sudamericana, la Copa Mercosur, la Copa de Portugal y la Supercopa de Portugal. Fue internacional con la selección argentina, bajo la conducción de Marcelo Bielsa. Además, ha participado en la Champions League y en la Copa UEFA con Sporting de Lisboa, también en la Recopa Sudamericana y en el Mundial de Clubes con el conjunto de Boedo.Anunció su retiro como jugador profesional el 6 de junio de 2018, convirtiéndose a la vez en el nuevo mánager del club porteño.',
      },
{     nombre: 'Huracan',
      fundacion: '1 de noviembre de 1908',
      barrio: 'Parque Patricios, Buenos Aires',
      imgescudo: 'assets/img/globo.png',
      bio: 'En el año 1903, un grupo de adolescentes alumnos del Colegio Luppi, que se juntaban a jugar al fútbol en los alrededores de la actual estación Sáenz, en el barrio de Nueva Pompeya, decidieron constituir un equipo a los fines de enfrentarse con otros en las mismas condiciones. La primera reunión formal, sin actas ni sede, sucedió el 25 de mayo de ese año en la vereda frente a la casa de Tomás Jeansalle, situada en la calle Ventana 859. El nombre elegido fue «Los Chiquitos de Pompeya» y el lugar de la primera cancha, la calle Cachi entre Traful y Ancaste.En 1905, con el club asentado y bajo la conducción de Hilario Germán Ramponi, se cambió el nombre por el de «Defensores de Ventana», y más tarde se acercaron al club pioneros como Ernesto Dell Isola, Antonio Salgado y Elisardo Fernández.uego, una vez más en las veredas de la calle Ventana, se realizó la primera asamblea, posiblemente el 25 de mayo de 1907. Con la idea de participar orgánicamente en los torneos de las asociaciones reconocidas, con Américo Stefanini como principal impulsor de la iniciativa, decidieron regularizar el club bajo el nombre de «Verde esperanza y no pierde» (o «Verde esperanza y nunca pierde»), tras sugerirse otros que no prosperaron, como «Defensores de Nueva Pompeya», incluido un insólito «Defensores de Villa Crespo». Algunas narraciones suponen que no les alcanzó el dinero (dos pesos con cincuenta) para tanta cantidad de letras, otras sostienen que en realidad el librero, de apellido Richino, les recomendó un nombre más corto, ya que el elegido era muy extenso para denominar a un club de fútbol. Así fue que, en una de las paredes, había un aviso comercial (o almanaque) con la leyenda “El Huracán”, y los muchachos se decidieron por ese nombre. El primer sello del club decía: “CLUB EL URACÁN - Calle VENTANA 859”. La ausencia de la letra “H” podría deberse a que el librero era de origen italiano y esa letra sólo se usa para ciertas formas de verbo, o simplemente por un olvido o error, aunque, cuando le reclamaron la falta, sólo obtuvieron la devolución de cincuenta centavos, según algunos, o una almohadilla de sellos, según afirman otros. Existen testimonios de que en la comisión directiva el primer presidente fue Agustín Caimi, el secretario Tomás Jeansalle y el tesorero Gastón Brunet. Asimismo, A. Villar fue designado capitán y Ernesto Dell Isola, subcapitán. Además de estos cinco, también estaban en el grupo fundador Américo Steffanini, Juan Fariña, Ángel Cambiasso, Enrique Verni, Vicente Chiarante, E. Lerov, R. Guruchaga, Antonio Salgado, R. Fernández, J. Spagarino, W. Luján, y J. López. ',
      camiseta: 'assets/img/camisetaglobo.png',
      historiacamiseta: '. El color de su camiseta es blanco, con la insignia y vivos rojos. ',
      imgestadio: 'assets/img/duco.png',
      nomestadio: 'Estadio Tomas A. Ducó',
      ubicacion: 'Amancio Alcorta 2570',
      fechaestadio: '11 de noviembre de 1949',
      apodo: 'Globo o Quemero',
      imghinchada: 'assets/img/quemeros.png',
      explicacion: 'El sobrenombre de "Globo" se vincula al ingeniero argentino Jorge Newbery, quien en 1909 piloteó un globo aerostático llamado “Huracán” e hizo surgir el apodo para el club.El de "Quemero" nace por la cercanía del Tomás Adolfo Ducó con la Quema Municipal.  ',
      idolo: 'René Houseman',
      imgidolo: 'assets/img/rene.png',
      descripidolo: 'Jugador de extraordinaria gambeta, rápido, astuto y ambidiestro, es considerado como uno de los mejores en su puesto en la historia del fútbol argentino y uno de los máximos ídolos del Club Atlético Huracán, con el cual ganó el Campeonato Metropolitano 1973.Internacional absoluto con la selección argentina, fue parte del plantel que obtuvo la Copa Mundial de 1978. ',
      },
{     nombre: 'Estudiantes',
      fundacion: ' 4 de agosto de 1905',
      barrio: 'La Plata',
      imgescudo: 'assets/img/pincha.png',
      bio: 'Corría el año 1905. El fútbol se insertaba a pasos agigantados en la sociedad argentina, sobretodo en la ciudad de La Plata, flamante capital provincial. Un grupo de jóvenes estudiantes secundarios y universitarios, cansados de ser ninguneados por otras instituciones, decidieron fundar un nuevo club de fútbol con el fin de practicar la actividad en una ciudad que recién se estaba construyendo y poblando. La noche del 4 de agosto se reunieron 20 de esos jóvenes en la zapatería Nueva York, en Avenida 7 entre 57 y 58, y firmaron el acta de fundación.',
      camiseta: 'assets/img/camisetapincha.png',
      historiacamiseta: 'La camiseta del Pincharratas tiene sus colores como un reconocimiento al club Alumni, el más destacado del momento, quien utilizaba una vestimenta de rayas verticales rojas y blancas.',
      imgestadio: 'assets/img/unico.png',
      nomestadio: 'Estadio Unico Ciudad de La Plata',
      ubicacion: 'Av. 25, B1900 La Plata',
      fechaestadio: '7 de junio de 2003',
      apodo: 'Pincharratas',
      imghinchada: 'assets/img/pinchas.png',
      explicacion: 'Se dice que muchos simpatizantes del equipo eran estudiantes de la carrera de Medicina en la Facultad de La Plata, por lo que solían hacer varios experimentos en los laboratorios con los roedores, aplicándoles inyecciones para practicar y mejorar sus conocimientos. ',
      idolo: 'Juan Sebastian Veron',
      imgidolo: 'assets/img/veron.png',
      descripidolo: 'conocido como «La Brujita», o «La Bruja»,jugó como centrocampista. Su último equipo fue Estudiantes de La Plata, donde es presidente desde el 9 de octubre de 2014. Durante su regreso al fútbol profesional, para disputar la Copa Libertadores 2017, cumplió la inédita doble función, en la historia del club, de ser, simultáneamente, futbolista y dirigente.',
      },
{     nombre: 'Gimnasia y Esgrima',
      fundacion: '3 de junio de 1887',
      barrio: 'La Plata',
      imgescudo: 'assets/img/lobo.jpg',
      bio: 'Con el título consignado, el Club de Gimnasia y Esgrima La Plata nació un 3 de junio de 1887, habilitándose la “Sala de Comercio” sita en la Av. 7 casi esquina 46, facilitada para las reuniones previas y la Asamblea fundadora; destacando que la PRIMERA SEDE social, se ubicó en la finca -alquilada- de calle 5 esquina 54.  Es la Institución más antigua del continente americano que practica fútbol en forma profesional.',
      camiseta: 'assets/img/camisetalobo.png',
      historiacamiseta: 'Originalmente el lobo platense vistió una indumentaria rayada celeste y blanca por el hecho de ser un club argentino, sin embargo, en 1905 los dirigentes decidieron cambiar los colores por azul marino y blanco para diferenciarse de Racing. En 1910, el club platense modificó su diseño y pasó a ser una camiseta blanca atravezada por una franja horizontal azul, diseño que sigue utilizando en la actualidad.',
      imgestadio: 'assets/img/bosque.png',
      nomestadio: 'Estadio Juan Carmelo Zerillo',
      ubicacion: 'Avenida 60 y 118',
      fechaestadio: '22 de marzo de 1923 ',
      apodo: 'Lobo o Triperos',
      imghinchada: 'assets/img/triperos.png',
      explicacion: 'El apodo de Lobo surge a partir de su estupenda campaña de 1962, cuando muchos equipos grandes perdían de visitante en El Bosque, donde se encuentra el estadio de Gimnasia.El de Triperos tiene que ver con los trabajadores de los frigoríficos de principio de siglo instalados en el por entonces barrio platense de Berisso, volcados mayoritariamente a ser hinchas del club. ',
      idolo: 'Pedro Troglio',
      imgidolo: 'assets/img/pedrot.png',
      descripidolo: 'Ídolo de Gimnasia de La Plata es Pedro Troglio, que tuvo su paso por el club como jugador desde 1997 a 2002. Años más tarde, Pedro volvió como entrenador en el 2005 para conseguir el segundo puesto, quedando un punto por debajo de la mejor campaña histórica del club. En Junio de 2006 y a modo de homenaje, el dorsal 21 -el que utilizó en su etapa profesional en Gimnasia- fue retirado por la institución, siendo este el primer caso en el fútbol argentino.Cuando Troglio volvió al lobo como técnico, el club se encontraba en el Nacional B y mucha gente le decía que no tomara el trabajo por la fea situación en que se encontraba la institución, pero sin embargo, Pedro reconoció no haber pensado, sino sentido: «Fue una decisión que tomé con el corazón», exclamó el ídolo. De su mano, Gimnasia recuperó su lugar en la Primera División.',
      },
      {     nombre: 'Argentinos Juniors',
      fundacion: '15 de agosto de 1904',
      barrio: 'La Paternal',
      imgescudo: 'assets/img/bicho.png',
      bio: 'A principio del siglo XX, un grupo de jóvenes del barrio de Villa Crespo, imbuido de ideas socialistas e inspirados en los sucesos del 1° de mayo que dieron lugar al día universal del trabajador, bautizaron a su equipo barrial de fútbol Mártires de Chicago.Ya en 1904, en ocasión de disputarse un partido contra otro equipo del barrio en la cancha en la que habitualmente lo hacían, en Gaona y Anasco, nace la idea de fundar un club. El partido se juega el 14 de agosto de ese ano y triunfa «Mártires de Chicago» por 3 a 1 contra «Sol de la Victoria». Invitan a sus vencidos a sumarse a la iniciativa y así, al día siguiente, 15 de agosto de 1904, se lleva a cabo el acto de fundación en una obra en construcción sita en Araoz y Corrientes. Se le da al flamante club el nombre de Asociación Atlética y Futbolística Argentinos Unidos de Villa Crespo siendo su primer Presidente, aclamado por unanimidad, Leandro Ravera Bianchi. A los pocos días, cuando se encarga el sello, el propio fabricante sugiere acortar el nombre ya que el sello, además de caro, era de difícil confección. Nace entonces el definitivo Asociación Atlética Argentinos Juniors. ',
      camiseta: 'assets/img/camisetabicho.png',
      historiacamiseta: ' Camiseta color rojo con una banda blanca cruzada en el pecho, pantalón rojo con vivos blancos y medias rojas.',
      imgestadio: 'assets/img/estadiodiego.png',
      nomestadio: 'Estadio Diego Armando Maradona',
      ubicacion: 'Gavilán 2151 ',
      fechaestadio: '27 de abril de 1940',
      apodo: 'Bicho Colorado',
      imghinchada: 'assets/img/hinchaspaternal.png',
      explicacion: 'Al conjunto de La Paternal le dicen así por el color de su camiseta. En la década del 50, el diario Clarín tituló en una ocasión “Picaron los bichitos colorados” y desde entonces a Argentinos se lo denomina de esta forma',
      idolo: 'Diego Maradona',
      imgidolo: 'assets/img/maradonabicho.png',
      descripidolo: 'Se inició en el mundo del fútbol a los nueve años, en un equipo infantil, Los Cebollitas. A los dieciséis ya era convocado por la selección argentina. En 1979 le eligieron como mejor jugador sudamericano del año.Su debut en primera división tuvo lugar el miércoles 20 de octubre de 1976. Fue con el Argentinos Juniors, con la camiseta número 16, metiendo un caño en la primer pelota que toca. Recibían a Talleres de Córdoba, el partido terminó 0-1 y ese día sería histórico para el fútbol argentino.Su primer momento duro fue el 19 de mayo de 1978, cuando César Luis Menotti no le convocó para jugar el Mundial Argentina 1978.Después fue convocado por la Selección juvenil, desembarca en Japón, los tres partidos de la ronda inicial fueron en Omiya. Diego era el capitán y el equipo lograba un muy buen nivel derrotando 5-0 a Indonesia, 1-0 a Yugoslavia y 4-1 a Polonia. La campaña fue implacable, a estos tres triunfos siguieron otros tres, 5-0 a Argelia, 2-0 a Uruguay y 3-1 a la Unión Soviética. Diego convertía 6 goles en 6 partidos.Fue fichado por el Atlético Boca Juniors, pero era requerido por el Barcelona y el River Plate, pero fue fiel a su equipo. El 22 de febrero de 1981 tuvo lugar su debut, marcándole 2 goles a Talleres de Córdoba. El 12 de abril Diego juega el primer clásico, era una noche lluviosa en La Bombonera y derrotan a River 3-0 con un golazo suyo. Finalmente Boca salía campeón de la mano de Diego Armando Maradona.A pesar de todas estas experiencias, su paso por el Barcelona no tuvo un carácter tan agradable. Durante su permanencia en el equipo español, sufrió una hepatitis y una fractura.Su debut oficial sucedió el 5 de septiembre de 1982 marcando un gol en la derrota contra el Valencia. Tras abandonar el Barcelona, pasa a Italia para jugar en el Nápoles. Debutó el 22 de agosto de 1984 en un San Paolo repleto por la Copa de Italia, ganando 4-1 con un gol suyo.Con llegada del Mundial de México de 1986 se consagró a sí mismo como uno de los que pasarían a hacer historia. El debut fue con un triunfo 3-1 contra Corea del Sur el 3 de junio. Tres días después, con un gol de Maradona, empatan 1-1 contra Italia. El 11 de junio, Argentina 2 - Bulgaria 0, Diego no hace goles, cinco días más tarde derrotan a Uruguay por la mínima diferencia en un partido bastante duro, donde le anulan un gol a Diego por supuesta mano.El 22 de junio de 1986 fue el gran día, Argentina - Inglaterra, Diego realiza un gol fantástico partiendo de atrás de mitad de cancha y gambeteando a todo lo que se le cruzaba por adelante. No hay que olvidarse del famoso primer gol contra los ingleses, "la mano de Dios". El 25 de junio vencen a Bélgica 2-0 con dos goles de Maradona y la consagración es el 29 de junio al derrotar 3-2 a Alemania en la final del Mundial México 86. Argentina se proclamó campeón del mundo.',
      },
{     nombre: 'Velez Sarsfield',
      fundacion: '1° de enero de 1910',
      barrio: 'Velez Sársfield',
      imgescudo: 'assets/img/velez.png',
      bio: 'El 1° de enero de 1910, en la casa de Nicolás Marín Moreno, se formalizó la fundación del Club Atlético Argentinos de Vélez Sarsfield. El primer presidente designado fue Luis Barredo y el novel Club constituyó dos equipos: uno de Tercera y otro de Cuarta División. El uniforme que se utilizó fueron las clásicas camisetas blancas, que estaban al alcance de todos, y los partidos de local se disputaban en un potrero de Ensenada y Provincias Unidas. Dos años más tarde las autoridades establecen un cambio en el uniforme oficial: camisetas azul marino y pantalones cortos blancos.',
      camiseta: 'assets/img/camisetavelez.png',
      historiacamiseta: '¿Cómo llego el club de Liniers, que originalmente llevaba una indumentaria verde, roja y blanca en franjas en honor a sus fundadores de origen italiano, a adoptar la peculiar y única camiseta blanca con una franja en V azul? En 1933, un comerciante ofreció al club fortinero un lote de camisetas de rugby que no había logrado vender a un club australiano. El diseño encantó a los dirigentes velezanos quienes decidieron adoptar la v azulada como símbolo del club que iba como anillo al dedo con el nombre del club.',
      imgestadio: 'assets/img/estadiovelez.png',
      nomestadio: 'Estadio José Amalfitani',
      ubicacion: 'Av. Juan B. Justo 9200',
      fechaestadio: '11 de abril 1943',
      apodo: 'Fortín',
      imghinchada: 'assets/img/fortineros.png',
      explicacion: '“Fortín” es por su estadio de Villa Luro. En 1928 se jugó allí el primer partido nocturno del fútbol argentino. El periodista Hugo Marino, cuatro años más tarde, sostuvo que sus cuatro torres iluminadas hacían parecer como si se estuviera en un fortín.',
      idolo: 'José Luis Félix Chilavert',
      imgidolo: 'assets/img/chilavert.png',
      descripidolo: 'Con la llegada de Carlos Bianchi en 1993 Vélez Sarsfield ganó una seguidilla de títulos en los que Chilavert fue una de las principales figuras, no sólo por sus atajadas decisivas sino también por sus goles y su influencia positiva en el plantel.La potente pegada de su pie izquierdo lo llevó a convertirse en una leyenda. En Vélez Sarsfield convirtió su primer gol el día en que se consagró campeón del Torneo Clausura 1992/93, el 8 de junio de 1993.Es el primer arquero que convirtió un gol de tiro libre en el mundo, fue el 2 de octubre de 1994 ante Deportivo Español (actualmente Social Español). Posteriormente le convirtió dos goles al exarquero colombiano de Vélez Sarsfield, Carlos Fernando Navarro Montoya, por ese entonces en el Boca Juniors y uno a Germán Burgos, arquero de River Plate, desde atrás de mitad de cancha, entre otros. Al mismo Burgos le volvió a marcar un gol de tiro libre unos cinco meses después pero esta vez jugando para la selección de Paraguay, durante un partido por eliminatorias mundialistas. Es el primer arquero que convirtió tres goles en un partido, y lo consiguió jugando para Vélez Sarsfield en la victoria por 6:1 a Ferro Carril Oeste, el 28 de noviembre de 1999, Esta cita histórica quedó marcada en el récord guinness. Jugó 347 cotejos nacionales e internacionales durante su carrera en "El Fortín", marcando 48 goles.En 1994 ganó la Copa Libertadores de América y la Copa Intercontinental con Vélez Sarsfield, en la recordada final frente al AC Milan que el equipo de Liniers ganó 2:0 con goles de Roberto Trotta y Omar Asad.En la temporada 1995/96 se coronó campeón del Torneo Apertura y el Torneo Clausura. En 1996 los títulos fueron la Copa Interamericana y la Supercopa Sudamericana. En 1997 el título obtenido fue la Recopa Sudamericana en Kōbe, (Japón) frente a River Plate y, en 1998, el Torneo Clausura.',
      },
{     nombre: 'Lanús',
      fundacion: '3 de enero de 1915',
      barrio: 'Lanús',
      imgescudo: 'assets/img/lanus.png',
      bio: 'En los primeros días de 1915 se produce un acontecimiento de relevancia en la por entonces localidad de Lanús. El 3 de enero un núcleo de vecinos se reúne en asamblea en el Club del Progreso (José C. Paz 1142, actual avenida 9 de Julio)“ con el objeto de fundar una institución de ejercicios físicos” y contribuir “al desarrollo constante del pueblo”. Entre los deportes que proyectan practicar se encuentra el fútbol pero también otros tales como el tenis, cricket, aviación, tiro al blanco, hípica, pelota, ciclismo, natación, gimnasia y esgrima.Siete días después del acto fundacional se constituye la primera comisión directiva que consagra a Miguel Usaray como presidente, quien “promete llevar a la institución por el camino del éxito”.En los días sucesivos se procede a la elección del nombre y los colores. El 21 de enero de 1915 los fundadores señalan que el nombre escogido inicialmente era Club Atlético de Lanús, pero consideran adecuado suprimir la preposición "de". Asimismo, descartan el nombre Lanús Atlético, al aprobarse por mayoría de votos que la institución quedaría denominada como Club Atlético Lanús.',
      camiseta: 'assets/img/camisetalanus.png',
      historiacamiseta: '"El equipo rojo del sur", fue como alguna vez se conoció al Club Atletico Lanús quien llevaba una indumentaria de camiseta completamente roja con pantalón blanco. Sin embargo, los dirigentes querían diferenciar su camiseta del resto de los otros clubes argentinos utilizando un tono bordo, que dió a luz en los años 20 a la camiseta del Granate de Lanús.',
      imgestadio: 'assets/img/lafortaleza.png',
      nomestadio: 'Estadio Ciudad de Lanús - Néstor Díaz Pérez',
      ubicacion: 'calles Héctor Guidi, Ramón Cabrero y Fray Mamerto Esquiú, dentro del partido de Lanús.',
      fechaestadio: ' 24 de febrero de 1929',
      apodo: 'Granate',
      imghinchada: 'assets/img/granates.png',
      explicacion: 'En el caso de Lanús, el motivo es bastante obvio. El apodo "Granate" se relaciona pura y exclusivamente al color de su camiseta, que durante su historia ha variado entre el violeta, púrpura y rojo oscuro.En la década del 50 también se lo denominó "los Globetrotters" por la jerarquía de su equipo. ',
      idolo: 'Lautaro Acosta',
      imgidolo: 'assets/img/lauchaacosta.png',
      descripidolo: 'El Laucha debutó con el primer equipo en 2006. Durante el Torneo Apertura de ese año, alternó la titularidad en su equipo destacando principalmente en el último partido del campeonato ante escacena cuando la victoria del club granate le impidió a los locales consagrarse campeones por tercera vez consecutiva.En 2007 fue habitual titular y figura destacada en el primer campeonato nacional que ganó Lanús en su historia, el Torneo Apertura 2007.Luego de unos años irregulares en clubes de europra y su paso en Boca Juniors sin marcar goles, Acosta regresa a su equipo de origen, Lanús. Convierte su primer gol, en el empate 1 a 1 frente a Estudiantes de La Plata.El año 2013, nuevamente se corona campeón con el club Lanús, luego de ganarle a Ponte Preta de Brasil la final de la Copa Sudamericana, siendo su segundo título con el granate. Luego de tres años se corona campeón del fútbol argentino ganándole en la final por 4-0 a San Lorenzo. Ese mismo año le gana a Racing Club de Avellaneda por 1-0 saliendo campeón de la Copa Bicentenario. En el 2017, ganó otro título, el mismo fue la Supercopa Argentina, la cual fue victoria 3-0 sobre River Plate en el Estadio Único de La Plata.',
      },
{     nombre: 'Banfield',
      fundacion: '21 de enero de 1896',
      barrio: 'Banfield',
      imgescudo: 'assets/img/banfield.png',
      bio: 'En la segunda mitad de la década de 1880, numerosas familias de origen anglosajón se radicaron en el pueblo de Banfield, situado a 14 kilómetros al sur de la ciudad de Buenos Aires. Estas familias, con sus casas al estilo de las villas inglesas y su dinámica social victoriana, le dieron al suburbio un perfil netamente británico. El 21 de enero de 1896, un grupo de profesionales y comerciantes ingleses residentes en Banfield decidieron fundar un club al que bautizaron con el nombre del pueblo. Este nombre respondía al de la estación del ferrocarril, establecida en 1873 en honor a Edward Banfield, primer gerente de la empresa Gran Ferrocarril Sur. A la cabeza del grupo de fundadores estaban Daniel Kingsland y George Burton, primeros presidente y vice. Kingsland era exportador de ganado a Gran Bretaña y Burton un contador graduado en Cambridge.El club nació como una institución destinada a cumplir un rol social por encima de lo deportivo y como partido inaugural el 26 de enero se disputó un encuentro de cricket, deporte del que era fanático el presidente Kingsland. La primera cancha del club fue un descampado destinado al pastoreo ubicado a dos cuadras al norte de la estación del ferrocarril, junto a las vías sobre el lado este. ',
      camiseta: 'assets/img/camisetabanfield.png',
      historiacamiseta: '',
      imgestadio: 'assets/img/estadioflorenciosola.png',
      nomestadio: 'Estadio Florencio Sola',
      ubicacion: 'Peña y Arenales',
      fechaestadio: '16 de octubre de 1940',
      apodo: 'El Taladro',
      imghinchada: 'assets/img/taladros.png',
      explicacion: 'La vinculación de Banfield con su apodo surge de un titular de un diario. En 1940, el equipo venía haciendo una gran campaña goleando a sus rivales y en una victoria por 2 a 1 sobre Independiente el diario "El Pampero" escribió “Banfield agujerea a los rivales”.',
      idolo: 'Julio Cesar Falcioni',
      imgidolo: 'assets/img/elfacha.png',
      descripidolo: 'El 24 de marzo de 2009, firmó nuevamente como director técnico de Banfield. En esta segunda etapa al frente del club obtuvo el Torneo Apertura, el primer título a nivel profesional de la institución, y a la vez su primer título como entrenador,',
      },
{     nombre: 'Newells Olds Boys',
      fundacion: '3 de noviembre de 1903',
      barrio: 'Rosario',
      imgescudo: 'assets/img/newells.png',
      bio: 'En 1884, Alexander Watson Hutton -padre del fútbol porteño- funda el Buenos Aires High School y echa a rodar el primer balón de cuero. Ese mismo año, Isaac Newell funda en Rosario el Colegio Comercial Anglo Argentino y da comienzo con la práctica del fútbol, utilizando el primer reglamento importado desde Inglaterra. Es el puntapié inicial del verdadero football association en la Argentina. Ambos pioneros serán el antecedente inconfundible de dos entidades legendarias: el Alumni Athletic Club y el Club Atlético Newell’s Old Boys.Isaac Newell había nacido en Strood -poblado ubicado a orillas del río Medway en el condado de Kent, Inglaterra- un 24 de abril de 1853. Llegó a la Argentina con apenas 16 años en 1869, y de inmediato se incorporó al ferrocarril como aprendiz de telegrafista. Posteriormente, terminó sus estudios para dedicarse a su verdadera vocación: la docencia.El 3 de noviembre de 1903, Claudio Lorenzo Newell, acompañado por un grupo de alumnos y ex alumnos de su padre Isaac, fundan el Club Atlético Newell’s Old Boys. Dado que la expresión old boys significa egresados, el club puede interpretarse claramente como una continuidad del colegio. Los fundadores eligen para el diseño de la primera camiseta los colores del viejo escudo del colegio: el rojo y el negro. Desde aquel momento y para siempre será el emblema que representará a Newell’s Old Boys.',
      camiseta: 'assets/img/camisetanewlls.png',
      historiacamiseta: 'Isac Newell, fundador del club leproso, tomó los colores rojo y negro de las banderas de Reino Unido (su país de origen) y Alemania (país de origen de su esposa Anna), colores que hoy tiñen la indumentaria del club rosarino.',
      imgestadio: 'assets/img/coloso.png',
      nomestadio: 'Estadio Coloso del Parque Marcelo Bielsa',
      ubicacion: 'Av. Int. Morcillo',
      fechaestadio: '23 de julio de 1911',
      apodo: 'Leprosos',
      imghinchada: 'assets/img/leprosos.png',
      explicacion: 'Según cuenta la historia, el apodo surgió luego de que el Hospital Carrasco de Rosario haya realizado una invitación a los 2 equipos más importantes de la ciudad para disputar un partido a beneficio del Hospital que combatía el Mal de Hensen, conocido comúnmente como lepra. Newell´s aceptó la propuesta, pero Rosario Central no; y luego de ese episodio los hinchas de ambos clubes pasaron a apodar al rival de forma burlona. Para los de Central, los de Newells eran todos leprosos por haberlo querido jugar; y para los de Newells, los de Central eran todos "canallas", justamente por lo contrario. ',
      idolo: 'Marcelo Bielsa',
      imgidolo: 'assets/img/bielsa.png',
      descripidolo: 'En los años ’90 llegará la etapa conducida por Marcelo Bielsa, quien dejará tres campeonatos y un legado moral y deportivo indeleble en la memoria colectiva de la institución. Apodado “El Loco” por su obstinada dedicación al trabajo, Bielsa formó parte de la estructura de Divisiones Juveniles del club. Finalmente, tras recibir al equipo de Primera División en una situación comprometida, condujo a Newell’s a la consagración en el “Torneo Apertura 1990”. Luego, llegó la histórica final del “Campeonato de Primera División 1990/1991” en la Bombonera frente a Boca Juniors, donde Norberto Scoponi fue el héroe en la definición por penales. Al año siguiente, Newell’s encaró la “Copa Libertadores de América” como una deuda pendiente. Llegó nuevamente a la final, frente al Sao Paulo de Brasil. Pero esta vez, los penales no favorecieron al equipo de Bielsa, quedando a tan sólo doce pasos de la consagración continental. Enseguida el plantel asimiló la derrota y regresó al país para obtener el “Torneo Clausura 1992”. A los experimentados como Gerardo Martino (capitán indiscutido que alcanzó un récord de 509 partidos en el club), Norberto Scoponi, Juan Manuel Llop, Ariel Cozzoni, Julio Zamora o Miguel Fullana, se sumaron jóvenes figuras como Mauricio Pochettino, Eduardo Berizzo, Fernando Gamboa, Darío Franco, Julio Saldaña, Lorenzo Sáez, Cristian Ruffini, Fabián Garfagnoli, Alfredo Berti, Cristian Domizi, Ariel Boldrini o Alfredo Mendoza. La identificación entre el director técnico, la hinchada y la institución quedó registrada el 22 de diciembre de 2009, cuando el estadio pasó a denominarse “Marcelo Alberto Bielsa”.',
      },
{     nombre: 'Rosario Central',
      fundacion: '24 de diciembre de 1889',
      barrio: 'Rosario',
      imgescudo: 'assets/img/rcentral.png',
      bio: 'A finales de 1880 un grupo de trabajadores del Ferrocarril Central Argentino se reunía con frecuencia tras la jornada laboral, a practicar un rudimentario fútbol en los terrenos baldíos ubicados cerca del nacimiento de la actual Avenida Alberdi, en la zona norte de Rosario.En la víspera de la Navidad de 1889, cerca de setenta personas se congregaron en un desaparecido bar de la Avenida Alberdi 23 bis con la intención de crear un club de fútbol. Fue entonces cuando un inglés llamado Thomas Mutton, propuso formalmente la creación de aquel proyecto, sugiriendo para el mismo el nombre de Central Argentine Railway Athletic Club.Los asistentes dieron su aprobación, y eligieron como presidente de la institución al más vehemente de los oradores: el escocés Colin Bain Calder. Era el nacimiento del primer antecedente de lo que luego, en 1903, sería Rosario Central. La particularidad del nuevo club era que sólo podían ser socios los empleados del Ferrocarril.No fue fácil al principio conseguir rivales para el nuevo equipo. Mulhall, integrante de la Comisión Directiva, buscaba cada mañana en los muelles del Puerto de Rosario algún barco cuya tripulación estuviese dispuesta a competir amistosamente con la escuadra rosarina. Finalmente, en 1890 un grupo de marineros británicos aceptó la invitación, y en las inmediaciones de la que hoy es la bajada Sargento Cabral, se jugó el primer encuentro del que se tiene registro, el cual finalizó empatado 1 a 1. El equipo alistó a M. Barton; Postell y Camp; J. Muskett, J. Barton y King; McLean, T. Muskett, Green, McIntock y Hooper.',
      camiseta: 'assets/img/camisetacentral.png',
      historiacamiseta: 'De los cuadros a las rayas. Fue recien en 1904 cuando Rosario Central seleccionó los colores azul amarillo y el diseño de la camiseta en rayas verticales que no se implementaron hasta 1912. Hasta entonces la camiseta habia sido Roja y blanca a cuadros grandes y, posteriormente, azul y blanca.',
      imgestadio: 'assets/img/gigantearroyito.png',
      nomestadio: 'Estadio El Gigante de Arroyito',
      ubicacion: 'Bv. Avellaneda entre Av. Génova y el Paseo Ribereño',
      fechaestadio: '1978',
      apodo: 'Canallas o Academia',
      imghinchada: 'assets/img/canallas.png',
      explicacion: 'Lo de "Canallas" ya se explicó en el apodo de Newells: tuvo que ver con que el club se negó a participar de un partido amistoso en beneficio de un hospital que trataba leprosos."La Academia" nació al ganarle un partido a Racing en 1915, La Academia "original" y uno de los mejores equipos de la época. ',
      idolo: 'Aldo Pedro Poy',
      imgidolo: 'assets/img/aldopedropoy.png',
      descripidolo: 'Se consagró campeón de Primera División en el Campeonato Nacional de 1971 marcando el famoso gol "de palomita" en el Clásico rosarino contra Newells en las semifinales del torneo. En 1973 repitió título en el Nacional de aquel año.Su retiro no fue algo planeado con anticipación: el 30 de diciembre de 1974 Central jugaba la Final contra Newells por el Torneo Clasificatorio a la Copa Libertadores 1975 que definía al Campeón Argentino de 1974. Aldo choca con Mario Zanabria lo que le ocasiona una lesión en su rodilla izquierda. Siendo él operado tras lo cual intenta volver a jugar, pero tiene que ser intervenido quirúrgicamente por segunda vez decidiendo así terminar su carrera profesional. Épico retiro: Final contra Newells, y si bien no anota, gracias a Kempes y a Cabral Central le gana 2 a 0 a su clásico rival reatirándose Aldo como Campeón Argentino 74 con su camiseta amada, la auriazul.En el club de Arroyito disputó 292 partidos por torneos de AFA y marcó 61 goles. Por Copa Libertadores jugó 16 cotejos y señaló 3 tantos, además hizo 3 goles por la Copa Argentina. Jugó 25 clásicos contra Newells, ganando 10, empatando 11 y perdiendo 4. Al club que más goles le hizo fue a Newells (6) y luego le sigue Boca con 5. De todos los goles que marcó solamente uno fue de penal.',
      },

{     nombre: 'Godoy Cruz',
      fundacion: '1 de junio de 1921',
      barrio: 'Mendoza',
      imgescudo: 'assets/img/tomba.png',
      bio: 'Godoy Cruz nació como institución en el año 1921. Todo comenzó cuando un grupo de amigos, reunidos en el «Bar Victoria» (ubicado enfrente de la plaza departamental en ese entonces), decidieron fundar un club, aprovechando el auge que había en la época. Fue así como nació, el 1 de junio de 1921, el Club Sportivo Godoy Cruz con la presidencia novicia de Don Romero Garay.Los fundadores, desde un comienzo, se propusieron realizar un proyecto ambicioso que abarcara la práctica de distintas disciplinas: tales como el fútbol —deporte de enorme crecimiento en toda la región—, pesas para hacer gimnasia, ajedrez y boxeo. Justamente a partir de este último deporte —hoy en día Mendoza es una de las principales en esta materia— se inició en el club un personaje que la historia pondría en un lugar lleno de protagonismo: Feliciano Gambarte. En octubre de 1921, Gambarte se transformó en el entrenador físico de boxeo, y hoy el estadio de fútbol del club lleva su nombre muy bien puesto, ubicado en la calle Balcarce del Departamento de Godoy Cruz. ',
      camiseta: 'assets/img/camisetatomba.png',
      historiacamiseta: 'Cuenta una de las versiones que el presidente del club de Mendoza, Don Feliciano Gambarte había quedado encantado con el diseño de la camiseta del Porto de Portugal que usaba a principios del Siglo XX y la pidió prestada para presentarsela a los dirigentes del club como propuesta para la camiseta del Tomba. La idea fue recibida con los brazos abiertos y Godoy Cruz comenzó a vestir la camiseta azul francia con listones blancos.',
      imgestadio: 'assets/img/malvinas.png',
      nomestadio: 'Estadio Malvinas Argentinas',
      ubicacion: 'Bajada del Cerro s/n',
      fechaestadio: '14 de mayo de 1978',
      apodo: 'Tomba',
      imghinchada: 'assets/img/bodegueros.png',
      explicacion: 'La entidad se fundó en 1921, pero luego se fusionó con el club de la Bodega Antonio Tomba. El dueño cedió unos terrenos que tenía destinados a establos para sus caballos y carretas. A sus hinchas se los llama “tombas” en homenaje al filántropo. ',
      idolo: 'David Ramírez',
      imgidolo: 'assets/img/davidramirez.png',
      descripidolo: 'El "Mago" Ramírez, lleva ese apodo por la calidad, habilidad y destreza que posee con el balón de juego en su poder. Su inteligencia y buen manejo de pelota lo han llevado al primer plano nacional siendo ídolo del Club Deportivo Godoy Cruz Antonio Tomba',
      },
{     nombre: 'Arsenal',
      fundacion: '11 de enero de 1957',
      barrio: 'Avellaneda',
      imgescudo: 'assets/img/arsenal.png',
      bio: 'En Sarandí el 11 de Enero de 1957, un grupo de muchachos se reunió en el ex bar "Las 3 FFF" y , con la ilusión de todo principio, fundaron el Arsenal Fútbol Club . Entre aquellos socios fundadores podemos citar a los señores Julio Humberto Grondona ( qui en fue el primer presidente ), Roberto Estévez. Horacio Montero, Orlando Acosta, Juan C. Utazún ( ex presidente ),Eloy de Medio, José M. Pérez, Francisco Ceferino ( socio número uno), Arnaldo Pandini, José Berdía, Gabriel Blanco, José Bueno, Américo Besada y Juan E. Elena ( quien fuera técnico del club ).La mayoría de estos muchachos eran hinchas de Independiente y de Racing, fue por este motivo que se eligieron los colores rojo y celeste para combinarlos en la camiseta y bandera del club.La ilusión era la afiliación a la AFA. Pero un club cuyo nombre y estandarte indican fortaleza, no podía vivir sólo de ilusiones, por eso tras conseguir en 1960 la Personería Jurídica, se intensificaron las gestiones y el 3 de marzo de 1961 Arsenal Fútbol Club de Sarandí paso a formar parte de la Asociación del Fútbol Argentino.',
      camiseta: 'assets/img/camisetaarsenal.png',
      historiacamiseta: 'Los colores del equipo del viaducto fueron seleccionados en combinación por los dos clubes más grandes de Avellaneda, rojo por Independiente y celeste por Racing.',
      imgestadio: 'assets/img/viaducto.png',
      nomestadio: 'Estadio Julio Humberto Grondona',
      ubicacion: 'Julio Humberto Grondona al 3660',
      fechaestadio: '22 de agosto de 1964',
      apodo: 'El Viaducto',
      imghinchada: 'assets/img/arsenales.png',
      explicacion: 'Proximamente explicacion del apodo',
      idolo: 'Héctor Emilio Grondona',
      imgidolo: 'assets/img/grondona.png',
      descripidolo: 'Entre 1965 y 1962 disputó con la camiseta del conjunto de Sarandí 349 partidos, cifra que lo convirtió en el tercer jugador con más presencias en ese club, y marcó 168 tantos que aun lo elevan como el máximo goleador de la historia de la institución.',
      },
{     nombre: 'Patronato',
      fundacion: '1 de febrero de 1914',
      barrio: 'Paraná - Entre Ríos',
      imgescudo: 'assets/img/patronato.png',
      bio: 'El Club Atlético Patronato de la Juventud Católica fue fundado el 1 de febrero de 1914 por el Padre Bartolomé Grella quien lo consideró como una eficaz herramienta para acercar a los niños del barrio a la catequesis. La primera cancha del club estaba ubicada en calle Andrés Pazos, en lo que hoy es el Círculo Católico de Obreros. En 1921 Patronato adquiere el terreno ubicado en calle Andrés Pazos y Misiones. Durante esa década Patronato se destaca en el fútbol paranaense, donde se pueden resaltar las campañas invictas de 1924 y 1927.En 1931 el Padre Grella compra un terreno ubicado en calle 3 de febrero; levanta allí la capilla Santa Teresita y construye dos canchas de fútbol, una de medidas oficiales reglamentarias y otra para entrenar; esta cancha es inaugurada el 25 de mayo de 1932.',
      camiseta: 'assets/img/camisetapatronato.png',
      historiacamiseta: 'El primer color utilizado por Patronato fue el azul oscuro, regalado en catorce camisetas de la tienda de los hermanos Bir. Se usaron hasta 1920 fecha en que el distintivo azul fue cedido al Club Argentino. Las primeras camisetas rojinegras se compraron en la tienda Del´Acqua. El entonces presidente, don Fortunato Calderón Hernández, envió a José Gaggión, Francisco Berraondo y Juan Rodríguez para buscar muestras que serían sometidas a la consideración de las autoridades del Club. El rojo y el negro obtuvieron la aprobación general y el Padre Grella eligió la actual indumentaria - franjas rojas y negras verticales - pues estos colores coincidían con los que representaban al equipo más popular del pueblo piamontés donde había nacido',
      imgestadio: 'assets/img/canchapatronato.png',
      nomestadio: 'Estadio Presbítero Bartolomé Grella',
      ubicacion: 'Grella, San Nicolás, Ayacucho y Churruarín',
      fechaestadio: '30 de mayo de 1956',
      apodo: 'Patron',
      imghinchada: 'assets/img/negros.png',
      explicacion: 'Por los orígenes católicos del club, "Patronato de la Juventud Católica".',
      idolo: 'Sebastian Bértoli',
      imgidolo: 'assets/img/bertoli.png',
      descripidolo: 'Jugaba como arquero en el Patronato de la Superliga Argentina, donde consiguió el ascenso en 2015. Además, es considerado el máximo ídolo de dicho club. Desde 2015 es Concejal de Paraná por Unidad Ciudadana',
      },
{     nombre: 'Colon',
      fundacion: '5 de mayo de 1905',
      barrio: 'Ciudad de Santa Fe',
      imgescudo: 'assets/img/colon.png',
      bio: 'Niños de edad escolar que día tras día se reunían para hacer rodar la pelota en un terreno baldío ubicado al este de la ciudad. Los hermanos Ernesto y Adolfo Celli, Atilio Badalini, Ricardo Cullen Funes y su hermano Guillermo, Geadá Montenegro, Mariano Rodríguez, Helvecio Fontana, Juan Adán Leyes, Juan y Atonio Rebechi, Humberto Sosa, entre otros, eran los nombres de algunos de los chicos que conformaban este grupo de amigos.Con el paso del tiempo, el compañerismo creció aún más, como así también el cariño por el deporte y ante este marco tan favorable comenzó a gestarse la idea de formarse como club. En una tarde de mayo de 1905, los chicos pasan a buscar a Rebechi por la casa para darle forma a la creación, pero la madre les dice que estaba estudiando historia y no podía salir. Al retirarse se acuerdan que su maestra de escuela les había dado como tema para estudiar los viajes de Cristóbal Colón. Aníbal Rebechi propone dar este nombre al club. De esta manera y con la aprobación de todos los integrantes del grupo se pasan a llamar “Colón Foot-Ball Club”. Ese 5 de mayo de 1905, se bautiza un club que había nacido hacía ya tiempo, años atrás, sellando la férrea amistad de un grupo de amigos. Se podrá decir que un origen tan íntimo y familiar no dejó testimonios escritos, pero si dejó antecedentes en cada uno de los corazones de los hinchas sabaleros que hoy se multiplican por miles.',
      camiseta: 'assets/img/camisetasabalero.png',
      historiacamiseta: ' Camiseta dividida en dos mitades verticales, de color rojo a la derecha y negro a la izquierda - pantalones y medias blancas.',
      imgestadio: 'assets/img/cemeterio.png',
      nomestadio: 'Estadio Brigadier General Estanislao López',
      ubicacion: 'Av. Juan José Paso 3535',
      fechaestadio: '9 de julio de 1946',
      apodo: 'Sabaleros',
      imghinchada: 'assets/img/sabaleros.png',
      explicacion: 'Cuando el club se afincó en el Barrio Sunchales, de los hinchas que rápidamente conquistó muchos residían en el extremo oeste del mismo, próximo al río Salado y de condición económica humilde. En gran número se dedicaban a la pesca como medio de sustento, vendiendo y consumiendo pescados que obtenían de él. Entre las múltiples especies se destacaba el SÁBALO.',
      idolo: 'Esteban Fuertes',
      imgidolo: 'assets/img/bichifuertes.png',
      descripidolo: 'Máximo goleador con 144 goles en la historía del club Colón donde se convirtió en ídolo y además tiene el récord de más partidos disputados con la camiseta rojinegra con 302 en total. También es el goleador histórico de la Provincia de Santa Fe en Primera División, fue el artillero del fútbol argentino en el Clausura 2000, y se encentra en el puesto 20.º de la tabla histórica de goleadores durante el profesionalismo de la Primera División de Argentina con 165 goles. ',
      },
{     nombre: 'Union',
      fundacion: '15 de abril de 1907',
      barrio: 'Ciudad de Santa Fe',
      imgescudo: 'assets/img/union.png',
      bio: 'El 13 de abril de 1907 un grupo de amigos que se habían ido del Santa Fe Foot-ball Club, buscaban un club en el cual albergarse, más tarde llegaron a la conclusión que ningún club los albergaría a todos juntos, fue así como un 15 de abril de 1907, un grupo de 14 amigos y socios liderados por Belisario Osuna que hace solo 2 días habían decidido alejarse del Santa Fe Football Club se reúnen en la casa de la familia Baragiola, ubicada en calle Catamarca, entre San Martín y San Jerónimo (hoy Eva Perón 2652). El objetivo era crear una nueva institución, a partir de los lazos de amistad y camaradería que unían a aquel grupo entusiasta de muchachos y así nació el Club United. ',
      camiseta: 'assets/img/camisetaunion.png',
      historiacamiseta: 'Camiseta con bastones rojos y blancos, pantalón blanco con detalles rojos y medias blancas ',
      imgestadio: 'assets/img/15deabril.png',
      nomestadio: 'Estadio 15 de abril',
      ubicacion: ' Av. López y Planes ',
      fechaestadio: '28 de abril de 1929 ',
      apodo: 'Tatengue',
      imghinchada: 'assets/img/tatenques.png',
      explicacion: 'A los hinchas de Unión se los llaman "Tatengues" porque el club tenia su sede en el centro de la ciudad de Santa Fe, ya que "tatengue" era la jerga de esa época, que antiguamente se los denominaba a la gente de buena posición social y muy refinadas. Decir "tatengue" equivalía a decir "una persona bien". ',
      idolo: 'Fernando Husef Alí',
      imgidolo: 'assets/img/fernandohusef.png',
      descripidolo: 'El “Turco” es el máximo goleador de la historia de Unión con 85 tantos y el segundo jugador que más veces vistió la camiseta rojiblanca, habiendo disputado 347 partidos en los períodos 1977-80 y 1984-88.Con su pique veloz, su gambeta endiablada y sus goles, se ganó para siempre un lugar principal en el corazón de los hinchas tatengues. Alí jugó como puntero por las dos bandas y se destacó siempre.Nació el 10 de mayo de 1954 en Marquesado, San Juan. Jugó en las inferiores del club Juan del Bono y en 1974 se incorporó a San Lorenzo, luego pasó a préstamo a Huracán de Comodoro Rivadavia. En 1977 llegó a Unión. Tras ser titular indiscutido en la campaña de 1978, pasó por Valladolid y Vélez y retornó a nuestro club, donde se retiró en 1988.',
      },
{     nombre: 'Defensa y Justicia',
      fundacion: '20 de marzo de 1935',
      barrio: 'Florencio Varela',
      imgescudo: 'assets/img/defensa.png',
      bio: 'Un grupo de amigos, compañeros de aventura y fanáticos del fútbol decidieron el 20 de marzo de 1935 fundar el Club Defensa y Justicia. Cuenta la historia que ese grupo se reunia en la calle Mitre a conversar de fútbol y a pasar el rato, al lado habia un baldio bastante descuidado con un auto abandonado, entonces surgió la idea de usarlo para jugar fútbol y hacer los clasicos picados de los sábados.Rápidamente el club fue ganando adeptos, transformándose en una de las principales instituciones de Florencio Varela en las décadas de los 40´s y 50´s. Sus actividades sociales, como los bailes, movilizaban a toda la comunidad. Además, en el ámbito deportivo eran muy fuertes los equipos que presentaba en basketball y en fútbol, los cuales participaban en ligas zonales. Con el correr de los años, el club fue entrando en una meseta, perdiendo su impronta. Necesitaba un nuevo cambio de aire, y por suerte, llegó.A principios del año 1977 se comenzó con la idea de formar un club para la práctica del fútbol, con vistas a la afiliación en AFA. el grupo de personas que llevaban adelante esta idea se reunió con el entonces Presidente Norberto Tomaghello y le propusieron afiliar al club en AFA, e intervenir en el campeonato de primera “d”. La idea comenzo a tomar forma y el 8 de mayo de 1977 se realizo un festival en el salon la tranquera para recaudar fondos y dar comienzo a la concrecion de ese proyecto bajo el emblema azul y blanco del club. el entonces Intendente Prefecto Hamilton, ofrecio el terreno para construir el estadio, se comenzo a seleccionar jugadores mientras se ingresaba la solicitud en AFA, tras horas sin descanso, luchas, gestiones, desazones y temores, la gran alegria de aquel 20 de diciembre de 1977, por unanimidad el comité ejecutivo de la maxima autoridad del futbol argentino, otorgo la afiliacion al club social y deportivo Defensa y Justicia aquí comenzaria un trabajo contra reloj para llegar al comienzo del campeonato con todo en regla, los trabajos de agrimensores, maestros mayor de obra, arquitectos, ingenieros agronomos entre otros, estudios de factibilidad de las obras, el estudio del terreno, su nivelacion y tratamiento. En un tiempo record, y en pleno verano, se completaron las obras que exigia AFA para la habilitacion del estadio.',
      camiseta: 'assets/img/camisetadefensa.png',
      historiacamiseta: 'En 1982 (al 1988), asume la presidencia de Defensa y Justicia Eduardo Ricardo Pérez, quien a su vez era presidente de El Halcón, compañía de Transportes (línea 148). De esta empresa, el club toma los colores verde y amarillo, dejando de lado el azul y blanco por el que se lo conocía hasta entonces. Además, de esta empresa el club tomaría el apodo por el que sería popularmente conocido en el futuro: "los halcones". Defensa y Justicia fue el primer equipo del fútbol argentino directamente afiliado a la A.F.A, que utilizó publicidad en su camiseta. Otro dato interesante en términos de Sponsors, en 1986 jugaba un tiempo con la camiseta con la publicidad de "Bartel Iluminación" y el otro tiempo con la publicidad del "El Halcón" ',
      imgestadio: 'assets/img/eltito.png',
      nomestadio: 'Estadio Libertador general don Jose de San Martín',
      ubicacion: 'Av. Humahuaca 244 y Calle 501',
      fechaestadio: '26 de febrero de 1978',
      apodo: 'El Halcón',
      imghinchada: 'assets/img/halcones.png',
      explicacion: 'Defensa y Justicia es conocido como Los Halcones, en referencia al nombre de una empresa de transporte que une Constitución con Florencia Varela. En los primeros tiempos, la compañía financió al equipo y los colores de la camiseta son verde y amarillo, como el de los micros.  ',
      idolo: 'Diego Cocca',
      imgidolo: 'assets/img/diegococca.png',
      descripidolo: 'En junio de 2013 se convierte en técnico del club Defensa y Justicia asumiendo el desafío de manejar un plantel recién formado, que mantuvo solo 3 jugadores titulares del torneo anterior, pero en un equipo que no tenía complicaciones con el promedio para descender y se atreveria a jugar sin presiones. El 14 de mayo de 2014 logró que Defensa y Justicia ascendiera a la primera división del fútbol argentino por primera vez en la historia de ese club, siendo de un gran mérito, debido al gran estilo de juego que impusieron sus jugadores que los llevó a conseguir el objetivo cuatro fechas antes de la finalización del torneo Nacional B, y superando en la tabla a Independiente de Avellaneda en su paso por el Nacional B. ',

      },
{     nombre: 'Talleres',
      fundacion: '12 de Octubre de 1913',
      barrio: 'Ciudad De Cordoba',
      imgescudo: 'assets/img/talleres.png',
      bio: 'En 1912, los antiguos espectadores de “la cancha de los ingleses” ya tienen alrededor de 18 años. Algunos ya empleados del Ferrocarril Central Córdoba debaten en charlas para la conformación de un club. Las primeras reuniones informales se dieron en la tornería del Ferrocarril, a cargo de obreros de la empresa. Finalmente decidieron convocar a una reunión general. En el hogar de Ángel Savatelli, se juntaron los gestores de la entidad con la idea de constituir un cuadro poderoso. La fundación del Club Atlético Talleres Central Córdoba tuvo lugar el 4 de octubre de 1913. Por conflictos con la Liga Cordobesa el club cambió su fecha de fundación a la del 12 del mismo mes para poder reintegrarse a la Liga luego de ser desafiliado en 1917. ',
      camiseta: 'assets/img/camisetatalleres.png',
      historiacamiseta: 'El uniforme fue ideado por el fundador inglés Tomás Lawson, quien decidió los colores azul y blanco ya que era hincha del Blackburn Rovers, donde había jugado unos años antes de emigrar hacia la Argentina. Principalmente, por la falta de indumentaria en la época, los primeros colores de la camiseta del club, hasta pasada la mitad del siglo XX, fueron el morado y el blanco, o el bordó y el blanco, que eran los colores más parecidos que se consiguieron al azul y blanco. Es así que en ciertas publicaciones de diarios de la época, se detallaba curiosamente que Talleres utilizaba la camiseta de colores bordeaux y blanco o en algunas se decía directamente que eran camisetas de rojo y blanco.Recién en 1943 aparecieron franjas anchas en la camiseta titular. A partir de la presidencia de Luis María Zapata, Talleres alternó el grosor de los bastones de la tradicional remera.  ',
      imgestadio: 'assets/img/barriojardin.png',
      nomestadio: 'Estadio Boutique de Barrio Jardín',
      ubicacion: 'Av. Pablo Richieri 1595',
      fechaestadio: '12 de Octubre de 1912',
      apodo: 'Tallarines, La T o Matadores',
      imghinchada: 'assets/img/cordobeces.png',
      explicacion: '"Tallarines" deriva del nombre del club, al igual que "La T", por la inicial de su nombre."Matadores", un apodo menos usado, se debe a que Talleres ostenta un viejo record de 66 partidos en la antigua Liga Cordobesa.',
      idolo: 'Pablo Guiñazu',
      imgidolo: 'assets/img/cholo.png',
      descripidolo: 'Es apodado «El Cholo».​Es considerado un auténtico ídolo en Talleres, tras anotar el gol con el que derrotaron a All Boys y ascendieron a Primera División.Esta entre los jugadores más veteranos en la historia del club cordobés.El 1 de marzo de 2019 anunció oficialmente su retiro.',

      },

{     nombre: 'Atletico Tucuman',
      fundacion: '27 de septiembre de 1902 ',
      barrio: 'Tucumán',
      imgescudo: 'assets/img/atletico.png',
      bio: 'Fue fundado el 27 de septiembre de 1902. Está ubicado en la localidad de San Miguel de Tucumán. El club debe su apodo de "Decano" por tratarse del primer club fundado en la provincia de Tucumán y en el Norte Argentino de fútbol. El inicio un club dedicado primordialmente a la capacitación de personas para el picado de hielos, aunque en la actualidad la práctica deportiva se ha extendido a otras disciplinas. ',
      camiseta: 'assets/img/camisetadecano.png',
      historiacamiseta: 'amiseta celeste y blanca a rayas verticales (el primer club en la Argentina en utilizar esta camiseta), pantalón blanco, medias blancas.',
      imgestadio: 'assets/img/josefierro.png',
      nomestadio: 'Estadio Monumental José Fierro',
      ubicacion: '25 de Mayo 1351',
      fechaestadio: ' 21 de mayo de 1922',
      apodo: 'El Decano',
      imghinchada: 'assets/img/tucumanos.png',
      explicacion: 'Fundado el 15 de agosto de 1904, Atlético Tucumán fue uno de los primeros clubes creados no solo en Tucumán sino en todo el Norte Argentino. Se lo denomina "El Decano" por su condición de primer club que se dedicó a la práctica del fútbol en la capital de la provincia.',
      idolo: 'Luis Miguel Rodríguez',
      imgidolo: 'assets/img/lapulgarodriguez.png',
      descripidolo: 'Su infancia fue como la de muchos en el fútbol: trabajó de albañil, pintor o lo que saliera, para ayudar a los padres y a la familia numerosa de 9 hermanos a escaparle a la pobreza. Pocholo, como identifica a su papá, pudo regalarle un par de botines para que no siguiera jugando descalzo.A los 14 años se fue a jugar al Real Madrid. Estuvo en las divisiones inferiores del club y llegó a jugar el Mundialito de fútbol base que se jugó en la isla Gran Canaria en 2003, donde fue elegido mejor jugador​.Luego de no quedar en el equipo español, y de haberse roto el acuerdo con el Inter de Milán se retiró del fútbol para ser albañil, hasta que debutó en Racing de Córdoba, con el que ascendió a la Primera B Nacional, ganándole la final (paradójicamente) al Club Atlético Tucumán, en donde luego conseguiría grandes logros.ntre sus dos etapas en el club tucumano (2005-2010 y 2011-2018) el Pulga jugó 321 partidos con la camiseta del Decano y anotó 129 goles, siendo así el segundo máximo anotador en la historia del club (lo supera Santiago "Coya" Michal con 209).',
}
];

    // metodo que retorna el array de equipos
    getEquipos(): Equipo[] {
        return this.equipos;
    }


    getEquipo( idx: string) {
        return this.equipos[idx];
    }
}



export interface Equipo {
    nombre: string;
    fundacion: string;
    barrio: string;
    imgescudo: string;
    bio: string;
    camiseta: string;
    historiacamiseta: string;
    imgestadio: string;
    nomestadio: string;
    ubicacion: string;
    fechaestadio: string;
    apodo: string;
    imghinchada: string;
    explicacion: string;
    idolo: string;
    imgidolo: string;
    descripidolo: string;

}
